base: https://1000goals.blades.ninja
title: 🥷
brand: <i class="fa-regular fa-house fa-xs"></i>
header_sitenav_label: ""
header_links:
  - url: https://github.com/anyblades/1000goals.blades.ninja
    title: <i class="fa-solid fa-laptop-code fa-sm faded"></i>
footer_contents:
  - Content licensed [CC BY-SA 4.0](//github.com/anyblades/1000goals.blades.ninja/blob/master/content/LICENSE.md).
